### ISSUE TITLE
Email notification not working?

### ISSUE THREAD

**Issue by youngahn** [CCS-Lab/hBayesDM#14]
e.g., 

output = gng_m1("example", email="wooyoung.ahn@gmail.com")

I'm supposed to receive a notification email but don't.

**Comment by PluVian** [comment]
The mail server for the package `mail` seems closed now.

```r
> to <- "urisa12@gmail.com"
> subject <- "Hello from R"
> body <- "It works!"
> mail::sendmail(to, subject, body)
Error in file(con, "r") : 
  cannot open the connection to 'http://rmail.linhi.de/rmail.php?Email=urisa12@gmail.com&Passwort=rmail&Betreff=Hello<from<R&Nachricht=It<works!'
In addition: Warning message:
In file(con, "r") :
  cannot open URL 'http://rmail.linhi.de/rmail.php?Email=urisa12@gmail.com&Passwort=rmail&Betreff=Hello<from<R&Nachricht=It<works!': HTTP status was '404 Not Found'
```

There are several packages which you can use instead of the package `mail`:

- [CRAN - Package mailR](https://cran.r-project.org/web/packages/mailR/)
- [CRAN - Package sendmailR](https://cran.r-project.org/web/packages/sendmailR/index.html)

Both of packages require an SMTP server to send mail. Except for the [Restricted Gmail SMTP Server](https://support.google.com/a/answer/176600?hl=en), most of the SMTP servers require authentication, which means the package should contain pre-defined information for SMTP server(s) or contain some codes to set a user configuration for authentication. Well, I think it could make the package a little messy.

Rather than that, I suggest using a callback function as an argument instead of `email`. Whatever a user wants to do after the job is done, the user can define it in a custom function and pass it into a function in the `hBayesDM`. I think it can make users free to run what they want to do after analysis.

```r
callback <- function () {
  mailR::send.mail(from, to, subject, body, ...)
  # or
  sendmailR::sendmail(from, to, subject, body, ...)
  # and any other jobs to do after completion...
}
```

**Comment by youngahn** [comment]
The mailing feature is removed from v0.5.0.
