### ISSUE TITLE
No alpha negative learning rate

### ISSUE THREAD

**Issue by bgunasekera** [CCS-Lab/hBayesDM#143]
Hi,

I want to estimate the Q learning rate for my subjects from an fMRI trial. The trial contains positive and negative prediction error stimuli. 

In R, I ran the following model:
`output <- pst_gainloss_Q( data = thc, niter = 2000, nwarmup = 1000, nchain = 4, ncore = 4)`

I then noticed that following `plot(output)`, the figure for the negative learning rate is blank, despite having negatively weighted prediction errors in my data set. 

What could be the reason behind this? 

I have included the code below and attached the relevant csv data file.

Thank you for your help.

Best wishes,
Brandon

`data <- read.csv("C:/Users/bjgun/OneDrive - King's College London/CANDOWN/RL_matrix_Q.csv")`
`thc <- data[ which(data$drug =='THC'),]`

`output <- pst_gainloss_Q( data = thc, niter = 2000, nwarmup = 1000, nchain = 4, ncore = 4)`
`plot(output)`

[RL_matrix_Q.csv](https://github.com/CCS-Lab/hBayesDM/files/8080066/RL_matrix_Q.csv)

**Comment by JaeyeongYang** [comment]
Hi Brandon,

I tried running `pst_gainloss_Q` with your data, using the R codes below:

```r
library(rstan)
library(hBayesDM)

df <- read_csv('RL_matrix_Q.csv')
fit <- pst_gainloss_Q(df, niter = 2000, nchain = 4, ncore = 4)
```

For plotting the hBayesDM outcome, I got the same result you described.

```r
plot(fit)
```

![image](https://user-images.githubusercontent.com/11037140/154883368-7b39e7ab-80ed-4ab5-a5e7-38b6099e3dae.png)

Then, I took a look to its parameter estimates, and negative learning rates were leant to zero, which might cause this issue.

```r
summary(fit$fit)$summary %>%
  as.data.frame() %>%
  rownames_to_column('variable') %>%
  as_tibble() %>%
  filter(str_detect(variable, 'alpha_neg'))
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/11037140/154883506-65610f0a-bcfa-4a42-9fb8-3433adbe75f2.png">

As a comparison, when I ran this model with the example data, there was no issue:

```r
fit <- pst_gainloss_Q('example', niter = 2000, nchain = 4, ncore = 4)

plot(fit)

summary(fit$fit)$summary %>%
  as.data.frame() %>%
  rownames_to_column('variable') %>%
  as_tibble() %>%
  filter(str_detect(variable, 'alpha_neg'))
```

![image](https://user-images.githubusercontent.com/11037140/154884015-10dbb6b3-893d-4605-b220-11524b7c466c.png)
<img width="772" alt="image" src="https://user-images.githubusercontent.com/11037140/154884032-04d0753e-9197-4f7a-8ef4-63aa5555b960.png">

I figured out that your data includes negative rewards as outcomes, which seems to be the primary difference to the example data. I checked `pst_gainloss_Q` and its preprocessing function code, and as far as I know, there won't be an issue on processing negative rewards.

In brief, not plotting the negative learning rates seems to be due to near-zero estimates, and it would require a fix on hBayesDM. However, I'm not sure if there is an error on hBayesDM to provide zero negative learning rates. It might be better for you to check your data for that.

Best,
Jaeyeong

**Comment by bgunasekera** [comment]
Hi @JaeyeongYang 

Many thanks for this.

So I am clear:
Alpha_pos is the learning rate to positive rewards 
Alpha_neg is the learning rate to negative rewards?

Best wishes,
Brandon

**Comment by bgunasekera** [comment]
Sorry @JaeyeongYang 

A further question.

In addition to the aforenamed values of interest, I'm also interested in extracting the Q values for each participant. Where in the output model is this located / what is the code to access it? 

Best wishes,
Brandon

**Comment by JaeyeongYang** [comment]
Sorry for getting back to this issue late.

Here are my replies to your two questions:

1. The `pst_gainloss_Q` model uses different learning rate parameters for positive and negative prediction errors, not for positive and negative rewards. If you initially intended to use different learning rates for rewards and losses, unfortunately, there is no model available in the hBayesDM yet, which may require you to write your own one.
    * Cf. Stan code for `pst_gainloss_Q`: [link](https://github.com/CCS-Lab/hBayesDM/blob/develop/commons/stan_files/pst_gainloss_Q.stan#L68-L70)
2. That `pst_gainloss_Q` stan code is not written to extract Q values yet, and hBayesDM cannot provide such model-based regressors yet. If you want to extract them in a hurry, I recommend you to use the stan code directly by yourself, along with modifying the code to extract Q values in `transformed quantities` block. Here, I attach an example from `prl_fictitious` where extracts Q values as `ev_c` (expected value of chosen option) and `ev_nc` (expected value of non-chosen option).
    * Cf. `transformed quantities` block for `pst_gainloss_Q`: [link](https://github.com/CCS-Lab/hBayesDM/blob/develop/commons/stan_files/pst_gainloss_Q.stan#L75-L113)
    * Cf. Example of `transformed quantities` block (from `prl_fictitious`) to extract Q values: [link](https://github.com/CCS-Lab/hBayesDM/blob/develop/commons/stan_files/prl_fictitious.stan#L90-L172)

Best,
Jaeyeong
