### ISSUE TITLE
Change first argument from choosing a file to receiving a data.frame

### ISSUE THREAD

**Issue by paulhendricks** [CCS-Lab/hBayesDM#2]
This removes mutable state from each function

**Comment by youngahn** [comment]
Perhaps allow both a file and a data.frame as the first argument? If it is a text file, read the text file into a data frame.

**Comment by paulhendricks** [comment]
We can do that but I strongly discourage it because then each function has "mutable state", or in other words, each function can modify values in a parent environment. 

Here's a really good chapter by Hadley Wickham on Functional Programming and why functions with mutable state should be avoided (or at least used properly). http://adv-r.had.co.nz/Functional-programming.html

Creating an interface that takes data.frames also aligns better with "tidy" data, the idea that functions should accept a data.frame and return a data.frame. Here's another really good paper by Hadley Wickham on the subject: http://vita.had.co.nz/papers/tidy-data.pdf

**Comment by youngahn** [comment]
My suggestion was primarily for users' convenience - let's discuss further.

**Comment by dlemfh96** [comment]
#### Note:
Since the package now uses the `data.table` library,
It would be worth changing the code to read user data through `fread()` of the `data.table` package.
It explains itself as "Similar to 'read.table( )' but faster and more convenient."
Also, it seems to have auto separator detection (like `" "`, `"\t"`), auto line-endings detection (like LF, CRLF), and it seems to read files regardless of the extension (like `.csv`, `.txt`).

https://www.rdocumentation.org/packages/data.table/versions/1.11.8/topics/fread

Matters to consider are:
- `data.table` has some syntax differences from `data.frame`, so developers should be aware.
- End users may want their `modelData$rawdata` object to be returned as a `data.frame` object. (Of course, this could easily be handled by passing `rawdata` through `as.data.frame()` before returning it to the user.)

**Comment by dlemfh96** [comment]
#### Update:
`hBayesDM_model.R` has been changed to use `fread`.

![image](https://user-images.githubusercontent.com/37664182/48192002-efeb4c80-e389-11e8-8bd3-08649d903dab.png)

However, separator is fixed to `"\t"` because `fread` shows trouble reading space-delimited files that have missing values.
Currently, `fread` is set to operate exactly the same way as before (that is, as with `read.table`), just quicker.

See this [commit](https://github.com/CCS-Lab/hBayesDM/commit/415660ffd99351598f831b7ea48c5e9c9550d6be) for more.
